# CALL BASE IMAGE WITH UBUNTU 18.04
FROM ubuntu:18.04

# COPY FILE TO LOCAL CONTAINER
WORKDIR /app
ADD . .

# INSTALL MODULE
RUN apt-get update && apt install libeigen3-dev libomp-dev gcc git cmake make -y
WORKDIR /usr/local/include
RUN cp -r /usr/include/eigen3/Eigen .

# RUNNING GOOGLETEST
WORKDIR /app/clara_test
RUN git clone https://github.com/google/googletest.git -b release-1.11.0
WORKDIR /app/clara_test/googletest
RUN mkdir build
WORKDIR /app/clara_test/googletest/build
RUN cmake .. && make install

# RUNNING MAIN TEST
WORKDIR /app/clara_test
RUN mkdir build
WORKDIR /app/clara_test/build
RUN cmake .. && make

# RUNNING BINARY FILE
WORKDIR /app/clara_test/build/tests
ENTRYPOINT ["./clara_testing"]
