name: Clara Test Windows Base

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build-and-testing:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Cygwin
        run: |
          choco install -y cygwin
          choco install -y eigen

      - name: testing grover search
        run: |
          g++ -pedantic -std=c++11 -Wall -Wextra -Weffc++ -fopenmp -g3 -DDEBUG -I /usr/include/eigen3 -I $HOME/clara/include testing/grover_search.cpp -o grover_search
          ./grover_search

      - name: testing channels
        run: |
          g++ -pedantic -std=c++11 -Wall -Wextra -Weffc++ -fopenmp -g3 -DDEBUG -I /usr/include/eigen3 -I $HOME/clara/include testing/channels.cpp -o channels
          ./channels
