name: Clara Test Linux Base With GPU Processing

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development


jobs:
  build-and-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install CUDA
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
          sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
          wget https://developer.download.nvidia.com/compute/cuda/11.3.1/local_installers/cuda-repo-ubuntu2004-11-3-local_11.3.1-465.19.01-1_amd64.deb
          sudo dpkg -i cuda-repo-ubuntu2004-11-3-local_11.3.1-465.19.01-1_amd64.deb
          sudo apt-key add /var/cuda-repo-ubuntu2004-11-3-local/7fa2af80.pub
          sudo apt-get update
          sudo apt-get -y install cuda
          export PATH=/usr/local/cuda-11.3/bin${PATH:+:${PATH}}
          export LD_LIBRARY_PATH=/usr/local/cuda-11.3/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
