name: Clara Test Linux Base With GPU Processing

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development


jobs:
  build-and-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: testing using Jimver cuda toolkit
        uses: cuda-toolkit
        with:
          cuda: '12.1.0'
        
      - name: test cuda-toolkit
        run: |
          echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
          echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
          nvcc -V
